Лаб №3 по Теории Принятия Решений

In [ ]:
import numpy as np

In [ ]:
import pandas as pd # Для красивого вывода.

Запрос количества альтернатив

In [ ]:
num = 4#@param

Создание матрицы

In [ ]:
arr = np.ones((num, num))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Матрица парных сравнений

In [1]:
for i in range(0, num):
  for j in range(i+1, num):
    print(f"Как {i+1} относится к {j+1}?")
    relation = np.float32(input())
    arr[i, j] = relation
    arr[j, i] = 1/relation
pd.DataFrame(arr, index=range(1, num+1), columns=range(1, num+1))

NameError: ignored

Ввод погрешности

In [ ]:
error = 0.00001#@param

Итерации

In [ ]:
Xarr = np.zeros(num)
Rarr = np.zeros(num)
Xarr[0] = 1
k = 0
S = 0
Xarr

array([1., 0., 0., 0.])

In [ ]:
while(True):
  k +=1
  for i in range(0, num):
    Rarr[i] = 0
    for j in range(0, num):
      Rarr[i] = Rarr[i] + arr[i, j] * Xarr[j]
  for i in range(0, num):
    Xarr[i] = Rarr[i]
  L = Xarr[0]
  for i in range(1, num):
    if Xarr[i] > L:
      L = Xarr[i]
  for i in range(0, num):
    Xarr[i] = Xarr[i]/L
  print(f"k = {k}, L = {L}, x = {list(Xarr)}")
  if ~(abs(L-S) > error):
    break
  S = L

print("Результат вычисления:")
print(f'Наибольшее собственное значение L = {L}');
print(f'Собст. вектор X: {list(Xarr)}');
print(f'Число итераций k = {k}');

k = 1, L = 8.999999932944775, x = [0.1111111119389534, 0.03703703731298447, 0.1111111119389534, 1.0]
k = 2, L = 7.101851852610707, x = [0.06258148676988125, 1.0, 0.6153846157074165, 0.2862730489890168]
k = 3, L = 5.823058298433365, x = [0.6370834755796106, 0.5458674513519995, 1.0, 0.19683981573976433]
k = 4, L = 6.2585721177153415, x = [0.5267266811714401, 0.3812542661772383, 0.736256203056866, 1.0]
k = 5, L = 7.740893877331935, x = [0.32526693100290993, 1.0, 0.8769013057800618, 0.7724003372096857]
k = 6, L = 8.291769585621715, x = [0.5171381636735205, 0.8121848934303415, 1.0, 0.489869517210255]
k = 7, L = 6.725355806235906, x = [0.5959718572823092, 0.6934429993234046, 1.0, 0.8193082310727985]
k = 8, L = 7.646976778867122, x = [0.49265679925157013, 0.8993433747045599, 1.0, 0.8542092360369241]
k = 9, L = 8.506867242217506, x = [0.503781114643644, 0.8573105412828559, 1.0, 0.6661204248141659]
k = 10, L = 7.597504979031731, x = [0.5461959065550261, 0.7815829761987663, 1.0, 0.73348071145390

Функция для нахождения собственных векторов/значений из NumPy для сравнения

In [ ]:
np.linalg.eig(arr)

(array([ 7.8145343 +0.j        , -1.79197826+5.07653842j,
        -1.79197826-5.07653842j, -0.23057779+0.j        ]),
 array([[-0.33001741+0.j        ,  0.21545313+0.28709279j,
          0.21545313-0.28709279j, -0.0244423 +0.j        ],
        [-0.52200661+0.j        , -0.64795961+0.j        ,
         -0.64795961-0.j        , -0.30773597+0.j        ],
        [-0.63067996+0.j        , -0.14324334+0.34730905j,
         -0.14324334-0.34730905j,  0.95091923+0.j        ],
        [-0.46993659+0.j        ,  0.25329747-0.4959881j ,
          0.25329747+0.4959881j ,  0.02130153+0.j        ]]))