Лаб №2 по Теории Принятия Решений

In [ ]:
import numpy as np

Исходные данные:

In [ ]:
arr = np.array([[180, 176, 176, 181, 177, 180], [67, 70, 68, 67, 68, 66], [850, 1002, 860, 818, 860, 801]], dtype=float).transpose()
arr

array([[ 180.,   67.,  850.],
       [ 176.,   70., 1002.],
       [ 176.,   68.,  860.],
       [ 181.,   67.,  818.],
       [ 177.,   68.,  860.],
       [ 180.,   66.,  801.]])

Вес каждого параметра:

In [ ]:
weight = np.array([0.4, 0.24, 0.36])
weight

array([0.4 , 0.24, 0.36])

Если True - для параметра оптимальна максимизация, если False - минимизация

In [ ]:
maximize = np.array([True, True, False])

Поиск максимума:

In [ ]:
max_crit = arr.max(0)
max_crit

array([ 181.,   70., 1002.])

Нормализация критериев:

In [ ]:
arr = arr/max_crit
arr

array([[0.99447514, 0.95714286, 0.84830339],
       [0.97237569, 1.        , 1.        ],
       [0.97237569, 0.97142857, 0.85828343],
       [1.        , 0.95714286, 0.81636727],
       [0.97790055, 0.97142857, 0.85828343],
       [0.99447514, 0.94285714, 0.7994012 ]])

In [ ]:
for n in range(0, len(maximize)):
  if ~maximize[n]:
    arr.transpose()[n] = 1 - arr.transpose()[n] 
arr

array([[0.99447514, 0.95714286, 0.15169661],
       [0.97237569, 1.        , 0.        ],
       [0.97237569, 0.97142857, 0.14171657],
       [1.        , 0.95714286, 0.18363273],
       [0.97790055, 0.97142857, 0.14171657],
       [0.99447514, 0.94285714, 0.2005988 ]])

Поиск обобщённой функции:

In [ ]:
arr *= weight
arr

array([[0.39779006, 0.22971429, 0.05461078],
       [0.38895028, 0.24      , 0.        ],
       [0.38895028, 0.23314286, 0.05101796],
       [0.4       , 0.22971429, 0.06610778],
       [0.39116022, 0.23314286, 0.05101796],
       [0.39779006, 0.22628571, 0.07221557]])

In [ ]:
func = arr.sum(1)
func

array([0.68211512, 0.62895028, 0.6731111 , 0.69582207, 0.67532104,
       0.69629134])

In [ ]:
func.max()

0.6962913383966085

Результатом будет номер оптимального двигателя.

In [ ]:
result = list(func).index(func.max()) + 1
result

6